# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.24.2
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
numpy_linalg_lapack_lite:
    language = c
Supported SIMD extensions in this NumPy install:
    baseline = 
    found = 
    not found = 
None


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
N = np.zeros((10,))
print(N)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print("Размер масива: ",
      N.size)

Размер масива:  10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help( np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vec = np.zeros((10,))
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vecRange = np.arange(10, 50)
print(vecRange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
revVec = np.arange(0, 50)
revVect = revVec[::-1]
print(revVect)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
M = np.arange(0, 9)
M.shape = (3, 3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
NoZeroArrayItems= np.array([1,2,0,0,4,0])
np.nonzero(NoZeroArrayItems)

(array([0, 1, 4], dtype=int32),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
IdentityMatrix = np.eye(3)
print(IdentityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
randomValues = np.random.random((3,3,3))
print(randomValues)

[[[0.90663346 0.33937698 0.50259973]
  [0.21183754 0.27197871 0.83893787]
  [0.64536522 0.75049744 0.11515041]]

 [[0.03466316 0.36596116 0.49558413]
  [0.71350778 0.66379803 0.52637914]
  [0.77649323 0.36432252 0.68899258]]

 [[0.43098569 0.82370372 0.76303207]
  [0.36559607 0.18076112 0.13807066]
  [0.39451393 0.32634409 0.67505448]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
randomArray = np.random.random((10,10))
minArray, maxArray = randomArray.min(), randomArray.max()
print("array: ", randomArray)
print(f"min = {minArray}, max = {maxArray}")

array:  [[2.02764138e-01 8.45658023e-01 9.56637701e-01 9.91875281e-01
  7.94872724e-01 7.94432510e-01 2.16552830e-01 3.52332388e-01
  3.49432066e-01 3.37397488e-01]
 [2.82756452e-01 2.05446175e-01 7.16474021e-01 8.64779650e-01
  4.03445932e-01 3.99780641e-01 4.53711492e-02 9.62636968e-01
  9.84316712e-01 8.79850315e-01]
 [5.38546762e-01 6.11946325e-01 2.63033800e-01 8.31474513e-01
  1.19740446e-01 7.23529820e-02 5.12804847e-01 7.29356509e-01
  9.46161243e-01 9.92667099e-01]
 [9.17138341e-01 3.03633744e-01 7.64256417e-01 5.64583923e-02
  6.28225328e-01 3.91753647e-01 4.91910434e-01 4.11525841e-01
  6.78570291e-01 2.76078480e-01]
 [7.42096222e-01 7.02392438e-01 9.83971966e-01 8.07814196e-01
  1.65879879e-01 2.19183995e-01 9.49073791e-02 8.46632206e-01
  8.88904290e-01 9.04159619e-01]
 [7.35570340e-01 8.20737702e-01 3.57940445e-01 8.01621685e-01
  1.42073219e-01 3.78044283e-01 4.80706260e-01 9.85112068e-01
  4.39027917e-01 5.32497215e-01]
 [4.68659708e-01 2.04070335e-01 8.76253938e-01 6.4

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
randomVector = np.random.random(30)
meanValue = randomVector .mean()
print("vector: ", randomVector )
print("mean value:", meanValue)

vector:  [0.46990802 0.83248278 0.46475642 0.70111762 0.68888079 0.89658852
 0.84512555 0.65189164 0.80097799 0.81274096 0.67234614 0.82824883
 0.94249994 0.07387658 0.48500012 0.21204406 0.24010726 0.47402653
 0.77353477 0.76675235 0.64340084 0.15851728 0.4663268  0.82046822
 0.77788246 0.88005954 0.30004543 0.19013868 0.81169511 0.59858405]
mean value: 0.6093341770476383


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
array = np.ones((10,10))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
belowTheDiagonalMatrix = np.diag(1+np.arange(4),k=-1)
print(belowTheDiagonalMatrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
matrix = np.ones((10,10), dtype=int)
matrix[1::2,::2] = 0
matrix[::2,1::2] = 0
print(matrix)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
checkerboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
matrix = np.random.random((5,5))
print("matrix: ", matrix)
normalMatrix= (matrix - np.mean (matrix)) / (np.std (matrix))
print("normalize matrix: ", normalMatrix)

matrix:  [[0.68221416 0.93680145 0.98425651 0.11478279 0.15696065]
 [0.59741167 0.04015911 0.78621534 0.55202052 0.18308664]
 [0.13619936 0.91447638 0.03857897 0.64400458 0.33606428]
 [0.79889772 0.88102643 0.32553801 0.62552831 0.29743657]
 [0.93606851 0.32211649 0.21007708 0.40018058 0.30847523]]
normalize matrix:  [[ 0.63018469  1.45772956  1.61198389 -1.21427084 -1.07717022]
 [ 0.35453123 -1.45683773  0.96824417  0.2069857  -0.99224677]
 [-1.14465553  1.38516115 -1.46197402  0.50598311 -0.4949876 ]
 [ 1.00946868  1.27643092 -0.52920363  0.44592533 -0.62054833]
 [ 1.45534712 -0.54032539 -0.90451341 -0.28657533 -0.58466678]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype([("r", np.ubyte, (1,)),("g", np.ubyte, (1,)),("b", np.ubyte, (1,)),("a", np.ubyte,(1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
matr53 = np.arange(1,16)
matr53.shape = (5, 3)
print("matrix 1:\n", matr53)

matr32 = np.arange(1,7)
matr32.shape = (3, 2)
print("matrix 2:\n",matr32)

rezult = np.dot(matr53, matr32)
print("multiply matrix:\n", rezult)


matrix 1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
matrix 2:
 [[1 2]
 [3 4]
 [5 6]]
multiply matrix:
 [[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
array = np.arange(-11, 12)
print(array)

array[(3 < array) & (array < 8)] *= -1
print(array)

[-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6
   7   8   9  10  11]
[-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3  -4  -5  -6
  -7   8   9  10  11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = np.array([1,2,3,4,5,6,7,8,9,10])
print("Z: ", Z)


a = Z**Z
print("Z**Z:", a)

a = 2 << Z >> 2
print("2 << Z >> 2:", a)

a = Z <- Z
print("Z <- Z:", a)

a = 1j*Z
print("1j*Z:", a)

a = Z/1/1
print("Z/1/1:", a)

#a = Z<Z>Z # ValueError
print("Z<Z>Z: # ValueError")


Z:  [ 1  2  3  4  5  6  7  8  9 10]
Z**Z: [         1          4         27        256       3125      46656
     823543   16777216  387420489 1410065408]
2 << Z >> 2: [  1   2   4   8  16  32  64 128 256 512]
Z <- Z: [False False False False False False False False False False]
1j*Z: [0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j]
Z/1/1: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Z<Z>Z: # ValueError


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
array = np.arange(-0.5, 0.5, 0.1)
print(array)
print (np.copysign(np.ceil(np.abs(array)), array))

[-5.00000000e-01 -4.00000000e-01 -3.00000000e-01 -2.00000000e-01
 -1.00000000e-01 -1.11022302e-16  1.00000000e-01  2.00000000e-01
  3.00000000e-01  4.00000000e-01]
[-1. -1. -1. -1. -1. -1.  1.  1.  1.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
array1 = np.array([24, 17, -3, 0, 10, 11, 15, -7, 14, 5])
array2 = np.array([3, 4, -3, 0, 6, 11, 33, -10, 14, 8])
print(np.intersect1d(array1, array2))

[-3  0 11 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
_ = np.seterr(**defaults)

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2023-04-07
2023-04-08
2023-04-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
array = np.random.uniform(0,10,10)
print (array - array%1)
print (np.floor(array))
print (np.ceil(array)-1)
print (array.astype(int))
print (np.trunc(array))

[4. 7. 6. 0. 8. 4. 2. 1. 3. 7.]
[4. 7. 6. 0. 8. 4. 2. 1. 3. 7.]
[4. 7. 6. 0. 8. 4. 2. 1. 3. 7.]
[4 7 6 0 8 4 2 1 3 7]
[4. 7. 6. 0. 8. 4. 2. 1. 3. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
matrix = np.zeros((5,5))
matrix+= np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
arr_1 = np.linspace(0,1,11,endpoint=False)[1:]
print(arr_1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
array = np.random.random(10)
print(array)
array.sort()
print(array)

[0.82280727 0.97181724 0.73419466 0.32174769 0.07014786 0.49286828
 0.08238851 0.2125099  0.13907002 0.41224808]
[0.07014786 0.08238851 0.13907002 0.2125099  0.32174769 0.41224808
 0.49286828 0.73419466 0.82280727 0.97181724]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
array = np.zeros(10)
array.flags.writeable = False
array[0] = 1

<class 'ValueError'>: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
matr = np.random.random((10,2))
X,Y = matr[:,0], matr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.9920846  0.50634082 0.29866241 0.9112004  0.73891033 1.076183
 0.91173286 0.20880544 0.475193   0.46135365]
[0.46401728 1.51309625 0.74630763 1.21180932 1.23556703 0.59936361
 1.37353195 1.42577914 1.26968341 1.01239576]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
array = np.random.random(10)
print(array)
array[array.argmax()] = 0
print(array)

[0.71841001 0.19219582 0.19918001 0.98316651 0.01411291 0.44155644
 0.60127322 0.44918086 0.03948536 0.18473754]
[0.71841001 0.19219582 0.19918001 0.         0.01411291 0.44155644
 0.60127322 0.44918086 0.03948536 0.18473754]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [51]:
np.set_printoptions(threshold=None)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

66


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
Z = np.zeros(10, [ ('position', [ ('x', float, (1,)),
                                  ('y', float, (1,))]),
                   ('color',    [ ('r', float, (1,)),
                                  ('g', float, (1,)),
                                  ('b', float, (1,))])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.35742002 0.07729122 0.081815   0.52442348 0.19841912
  0.60078015 0.39482862 0.6198603  0.38320911]
 [0.35742002 0.         0.31129236 0.41135563 0.64659455 0.52763409
  0.26525176 0.09254477 0.2818238  0.29333437]
 [0.07729122 0.31129236 0.         0.10048112 0.47202737 0.27488286
  0.56770579 0.33471474 0.55889974 0.30596081]
 [0.081815   0.41135563 0.10048112 0.         0.45900777 0.21704288
  0.66516391 0.43403599 0.65734    0.37766199]
 [0.52442348 0.64659455 0.47202737 0.45900777 0.         0.66079906
  0.89636365 0.59561542 0.73774662 0.37663413]
 [0.19841912 0.52763409 0.27488286 0.21704288 0.66079906 0.
  0.74098525 0.58035915 0.80316462 0.58029611]
 [0.60078015 0.26525176 0.56770579 0.66516391 0.89636365 0.74098525
  0.         0.30079397 0.27110154 0.52405323]
 [0.39482862 0.09254477 0.33471474 0.43403599 0.59561542 0.58035915
  0.30079397 0.         0.22505954 0.22492516]
 [0.6198603  0.2818238  0.55889974 0.65734    0.73774662 0.80316462
  0.27110154 0.22505

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [55]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[83.04175   70.35703    3.2632763 24.309902  19.232632  29.93916
 88.89708   12.424324  75.65498   27.580639 ]
[83 70  3 24 19 29 88 12 75 27]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [57]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [58]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [59]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [60]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.46417169 -0.23429117  0.08388607  0.21773594 -0.4112927  -0.00748926
  -0.27703882  0.25655721 -0.43641135  0.34417239]
 [ 0.10977631 -0.53619139  0.09549469 -0.33902063  0.08183602  0.00890118
   0.14132173  0.14636141  0.37877295 -0.08725226]
 [-0.3288949  -0.00549487  0.30163616  0.24890535 -0.31156964  0.27456231
  -0.06707531 -0.23205637  0.21057603 -0.09058875]
 [-0.50628767 -0.06680908  0.06864843  0.3638979   0.11092262  0.33735005
  -0.3884334  -0.00086806 -0.14348194  0.22506115]
 [ 0.26063063  0.09990728  0.17684849  0.28685681 -0.25961485 -0.32704181
  -0.37001671  0.20829702  0.02197807 -0.09784494]]


#### 59. How to sort an array by the nth column? (★★☆)

In [61]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 7 3]
 [9 8 8]
 [2 6 2]]
[[2 6 2]
 [9 7 3]
 [9 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [63]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5407699936217414


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [64]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[7. 2. 5. 1. 1. 1. 5. 3. 3. 2.]
[13.  3.  9.  1.  1.  1.  9.  5.  5.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [68]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [69]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)


sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 52 46 47]
 [53 60 58 44]
 [46 53 44 50]]
[[52 52 46 47]
 [53 60 58 44]
 [46 53 44 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [70]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.40319411 0.63998767 0.19906383 0.53389869 0.70431089 0.36807937
 0.42886514 0.41929399 0.56374162 0.56844586]
0    0.403194
1    0.639988
2    0.199064
3    0.533899
4    0.704311
5    0.368079
6    0.428865
7    0.419294
8    0.563742
9    0.568446
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [71]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([0.95742951, 1.28379084, 1.29349268, 1.43708425, 1.47913062])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [73]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [74]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [75]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 41) ( 0, 58) ( 2,  3) ( 2, 83) ( 3, 83) ( 6, 60) ( 6, 82) (10, 73)
 (10, 83) (13, 30) (13, 60) (16, 76) (16, 94) (23, 25) (23, 95) (25, 95)
 (27, 55) (27, 78) (28, 49) (28, 87) (30, 60) (41, 58) (46, 59) (46, 74)
 (49, 87) (55, 78) (59, 74) (60, 82) (73, 83) (76, 94)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [76]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [77]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [78]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [79]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.15181458,  0.87404143,  0.83106622, -0.66636991,  0.03276151,
       -0.39269084, -0.34507292,  0.10832931,  0.58492943,  0.23645746,
        0.22866072, -0.54174194,  0.87272681, -0.3363407 , -0.24969929,
        0.97948628,  0.82437156, -0.44582198,  0.96224907,  0.31785087,
        0.38735125,  0.81400394,  0.73891596,  0.96483176,  0.87543022,
        0.82552709,  0.56268921, -0.69504914,  0.91161088,  0.31552407,
        0.87373825,  0.38760884, -0.49388814,  0.61213983,  0.72556768,
       -0.62463206,  0.90362317,  0.12126584, -0.12339166, -0.66013595,
       -0.15123998, -0.90853019, -0.95831985, -0.29980413,  0.0716508 ,
        0.97994766,  0.74331323, -0.78084571, -0.86201064,  0.76674704,
       -0.71949736, -0.73393157,  0.39417412, -0.09159418,  0.779034  ,
        0.78428136, -0.91916177, -0.05132251,  0.15458129, -0.27479888,
       -0.59971303, -0.89866668, -0.40792663,  0.61099418, -0.04947365,
        0.30884747, -0.3134027 ,  0.19985241,  0.58609006,  0.96

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [80]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.9152098   6.03301514  0.6193232   8.69887055  5.12541837  3.31133545
  5.47147145  6.44693558 12.66151029  0.10485492]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [81]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.06966978  5.45082173  1.89147105  4.58634337  4.51433326 10.13970707
   3.78825698  5.60882889  5.85601935  6.52889907]
 [ 1.75139227  2.40742504 12.74942886  0.38973369  3.86198705  5.77522803
   9.37239937  1.49191611  2.18882586  4.27782993]
 [ 1.83211517  8.16147981  6.8849372   1.61805709  2.55787395  3.87943245
  10.4116362   5.3830677   4.7844549   9.72004468]
 [ 3.19686964 10.23439209  0.94345055  1.53378667  3.57634217  7.15167741
   6.26587493 10.41285028 10.50706592 11.21827642]
 [ 8.29298035  1.23616111  5.17041442  9.31728112  6.50343077 14.79002239
   0.21615831  0.80121223  0.26150258  0.08174009]
 [10.48892552  6.71860367  8.36354194 12.85375964  7.63393042 18.2533305
   3.10001661  6.28209256  5.56062085  5.46075571]
 [ 6.90440379  0.75194537  4.68174579  7.58109391  5.43022085 13.07099534
   1.35889165  0.88738635  1.28420529  1.92299664]
 [ 1.02147881  3.31811672 15.54224019  4.45042766  2.14431775  9.76709709
   5.93211195  6.97377171  7.41853021  1.38353314]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [84]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [85]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [86]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [87]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 3]
   [4 4 4]
   [3 0 3]]

  [[0 3 1]
   [4 4 0]
   [0 3 1]]

  [[3 1 2]
   [4 0 2]
   [3 1 1]]

  [[1 2 2]
   [0 2 3]
   [1 1 3]]

  [[2 2 0]
   [2 3 4]
   [1 3 4]]

  [[2 0 0]
   [3 4 3]
   [3 4 0]]

  [[0 0 4]
   [4 3 0]
   [4 0 4]]

  [[0 4 2]
   [3 0 0]
   [0 4 1]]]


 [[[4 4 4]
   [3 0 3]
   [0 4 0]]

  [[4 4 0]
   [0 3 1]
   [4 0 1]]

  [[4 0 2]
   [3 1 1]
   [0 1 1]]

  [[0 2 3]
   [1 1 3]
   [1 1 0]]

  [[2 3 4]
   [1 3 4]
   [1 0 1]]

  [[3 4 3]
   [3 4 0]
   [0 1 1]]

  [[4 3 0]
   [4 0 4]
   [1 1 0]]

  [[3 0 0]
   [0 4 1]
   [1 0 1]]]


 [[[3 0 3]
   [0 4 0]
   [2 0 0]]

  [[0 3 1]
   [4 0 1]
   [0 0 2]]

  [[3 1 1]
   [0 1 1]
   [0 2 3]]

  [[1 1 3]
   [1 1 0]
   [2 3 0]]

  [[1 3 4]
   [1 0 1]
   [3 0 0]]

  [[3 4 0]
   [0 1 1]
   [0 0 3]]

  [[4 0 4]
   [1 1 0]
   [0 3 0]]

  [[0 4 1]
   [1 0 1]
   [3 0 1]]]


 [[[0 4 0]
   [2 0 0]
   [0 3 3]]

  [[4 0 1]
   [0 0 2]
   [3 3 2]]

  [[0 1 1]
   [0 2 3]
   [3 2 1]]

  [[1 1 0]
   [2 3 0]
   [2 1 1]]

  [[1 0 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [88]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  8 16  0  9]
 [ 8  9  8  5  8]
 [16  8  6 42 10]
 [ 0  5 42  9  9]
 [ 9  8 10  9  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [90]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [91]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [92]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [93]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [97]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [98]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.18 s ± 52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
200 ms ± 9.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
150 ms ± 7.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [99]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)